SELECT 	
		 a.INTEGRATION_ID
		,a.INTERFACE_NM
		,b.STATUS 
		,b.BUSINESS_ID 
		,b01.BUSINESS_NM	AS "업무명"
		,c.SYSTEM_ID 
		,c01.SYSTEM_NM  	AS "송신시스템명"
		,d.SYSTEM_ID 
		,d01.SYSTEM_NM  	AS "수신시스템명"
		,a.DATA_PR_DIR
		,a.APP_PR_METHOD
		,a.DATA_PR_DIR
		,a.REG_USER
		,a01.USER_NM 		AS "등록자명"
		,a.REG_DATE
		,a.MOD_USER
		,a02.USER_NM 		AS "수정자명"
		,a.MOD_DATE
  	  FROM TAN0201 a
INNER JOIN TAN0101 b
		ON a.INTERFACE_ID = b.INTERFACE_ID 
INNER JOIN TIM0301 b01
        ON b01.BUSINESS_ID = b.BUSINESS_ID 
INNER JOIN TAN0213 c
		ON a.INTERFACE_ID = c.INTERFACE_ID 
	   AND c.NODE_TYPE = '0'
	   AND c.SEQ = (SELECT max(SEQ) FROM TAN0213 WHERE INTERFACE_ID = c.INTERFACE_ID AND NODE_TYPE = '0')
INNER JOIN	TIM0101 c01 
		ON c01.SYSTEM_ID = c.SYSTEM_ID 
INNER JOIN TAN0213 d
		ON a.INTERFACE_ID = d.INTERFACE_ID 
	   AND d.NODE_TYPE = '2'	   
	   AND d.SEQ = (SELECT max(SEQ) FROM TAN0213 WHERE INTERFACE_ID = d.INTERFACE_ID AND NODE_TYPE = '2')
INNER JOIN TIM0101 d01
		ON d01.SYSTEM_ID = d.SYSTEM_ID
INNER JOIN tsu0101 a01 
		ON a01.USER_ID = a.REG_USER 
LEFT OUTER JOIN tsu0101 a02 
		ON a02.USER_ID = a.MOD_USER