SELECT 
	 a.INTERFACE_NM
	,a.INTEGRATION_ID
	,a.APP_PR_METHOD -- APP처리방식 
	,a.DATA_PR_METHOD-- 데이터처리방식 
	,a.DATA_PR_DIR   -- 데이터 처리방향 
  FROM TAN0201 a
 ;
 
SELECT 
	LEVEL1 , LEVEL2 , max(COMMENTS), count(CD)  
  FROM TSU0301
GROUP BY LEVEL1 , LEVEL2
ORDER BY 1, 2;



SELECT LEVEL1,LEVEL2, COMMENTS,  CD, NM, NM2 FROM TSU0301 WHERE LEVEL1 = 'IM' AND LEVEL2 = '01'
UNION 
SELECT LEVEL1,LEVEL2,COMMENTS, CD, NM, NM2 FROM TSU0301 WHERE LEVEL1 = 'IM' AND LEVEL2 = '02'
UNION 
SELECT LEVEL1,LEVEL2,COMMENTS, CD, NM, NM2 FROM TSU0301 WHERE LEVEL1 = 'IM' AND LEVEL2 = '12';

--------------------------------------------
-- 인터페이스 리스트 조회 - 공통코드 조인 SQL
--------------------------------------------  
	SELECT 
		 a.INTERFACE_NM
		,a.INTEGRATION_ID
		,a.APP_PR_METHOD 			-- APP처리방식 CD 
		,cd1.NM AS APP_PR_METHOD_NM -- APP처리방식 NM
		,a.DATA_PR_METHOD			-- 데이터처리방식CD
		,cd2.NM AS DATA_PR_METHOD_NM-- 데이터처리방식NM
		,a.DATA_PR_DIR   			-- 데이터 처리방향CD 
 		,cd3.NM AS DATA_PR_DIR 		-- 데이터 처리방향NM
	  FROM TAN0201 a
LEFT OUTER JOIN TSU0301 cd1 ON a.APP_PR_METHOD  = cd1.CD AND cd1.LEVEL1 = 'IM' AND cd1.LEVEL2 = '02'
LEFT OUTER JOIN TSU0301 cd2 ON a.DATA_PR_METHOD = cd2.CD AND cd2.LEVEL1 = 'IM' AND cd2.LEVEL2 = '12'
LEFT OUTER JOIN TSU0301 cd3 ON a.DATA_PR_DIR    = cd3.CD AND cd3.LEVEL1 = 'IM' AND cd3.LEVEL2 = '01'
	 WHERE a.DEL_YN = 'N'
	   AND a.REG_USER = 'iip'
	   AND a.INTEGRATION_ID LIKE 'U%'
	   AND a.APP_PR_METHOD = '0'
ORDER BY a.MOD_DATE DESC  
;


	SELECT 
		 a.INTERFACE_NM
		,a.INTEGRATION_ID
		,a.APP_PR_METHOD 			-- APP처리방식 CD 
		,(SELECT NM FROM TSU0301 cd1 WHERE a.APP_PR_METHOD  = cd1.CD AND cd1.LEVEL1 = 'IM' AND cd1.LEVEL2 = '02') AS APP_PR_METHOD_NM -- APP처리방식 NM
		,a.DATA_PR_METHOD			-- 데이터처리방식CD
		,(SELECT NM FROM TSU0301 cd2 WHERE a.DATA_PR_METHOD = cd2.CD AND cd2.LEVEL1 = 'IM' AND cd2.LEVEL2 = '12') AS DATA_PR_METHOD_NM-- 데이터처리방식NM
		,a.DATA_PR_DIR   			-- 데이터 처리방향CD 
 		,(SELECT NM FROM TSU0301 cd3 WHERE a.DATA_PR_DIR = cd3.CD AND cd3.LEVEL1 = 'IM' AND cd3.LEVEL2 = '02') AS DATA_PR_DIR 		-- 데이터 처리방향NM
	  FROM TAN0201 a
	 WHERE a.DEL_YN = 'N'
	   AND a.REG_USER = 'iip'
	   AND a.INTEGRATION_ID LIKE 'U%'
	   AND a.APP_PR_METHOD = '0'
ORDER BY a.MOD_DATE DESC  
;
